# .pre-commit-config.yaml
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit.git
    rev: v0.15.6
    hooks:
    -   id: ruff-check
        args: [--fix]
    -   id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v1.19.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
# -   repo: https://github.com/pytest-dev/pytest.git
#     rev: 9.0.2
#     hooks:
#     -   id: pytest
#         args: [--cov=src/stock_explorer]
